# Generated by Django 5.0.6 on 2024-05-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaprafka',
            name='lan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zaprafka',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
