# Generated by Django 5.0.6 on 2024-05-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_zaprafka_lan_zaprafka_lat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaprafka',
            name='lan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='zaprafka',
            name='lat',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
